### ISSUE TITLE
Broken environment

### ISSUE THREAD

**Issue by luizgribeiro** [open-feature/playground#245]
I've followed the steps provided in the readme but had the following error running the docker compose step:

```
openfeature-playground-otel-collector-1   | * error decoding 'exporters': unknown type: "jaeger" for id: "jaeger" (valid values: [f5cloud googlemanagedprometheus kafka skywalking sentry awsemf dataset parquet prometheus dynatrace file googlecloudpubsub loadbalancing otlphttp awss3 cassandra datadog pulsar sapm signalfx splunk_hec googlecloud instana loki zipkin alibabacloud_logservice awscloudwatchlogs awsxray elasticsearch awskinesis prometheusremotewrite sumologic otlp clickhouse influxdb tanzuobservability logging azuredataexplorer logicmonitor mezmo opencensus tencentcloud_logservice azuremonitor carbon coralogix logzio])
```

**Comment by beeme1mr** [comment]
I've updated the OTel collector config to use OTEL.

**Comment by luizgribeiro** [comment]
That was fast! I was trying to fix the issue to send a PR but had no success. Version pinning will definitely prevent this kind of issue.

Browsing the OpenFeature webpage I saw no references to the Playground. Is it on purpose?
It might be a valuable resource to try a more complex scenario after the 5 minutes guide and tutorials.
If needed, I could work on it
