### ISSUE TITLE
Golang SDK Implementation

### ISSUE THREAD

**Issue by davejohnston** [open-feature/playground#25]
I'd like to help out building a golang SDK implementation of the SDK.

- Can someone help point me to the minimum spec that must be implemented.
- Is there a mock service that can be used for testing
- Where would be the right location to create a repo

Any info from someone who's worked on one of the other SDKs would be much appreciated.

**Comment by agentgonzo** [comment]
Current spec (WIP) is here. https://github.com/open-feature/spec/blob/main/specification/flag-evaluation/flag-evaluation.md. I think it would be great for you to start doing the golang implementation of the SDK. It will help us validate the spec. 

There isn't a mock service (or any reference implementations of a provider) at the moment. You may have to do both in parallel. I think it'll be good to also have a simple reference implementation (eg, returning hard-coded values) for each language as well as 'real' (vendor-provided) implementations of the provider.

I'm sure one of the admins (@toddbaert @beeme1mr ) can set you up with a repo with permissions, but if not, feel free to create your own public repo in your own account and start there. it's pretty simple to move-and-rename repos after the fact.

**Comment by agentgonzo** [comment]
... oh... I just remembered that golang isn't quite as happy when you move repos. Yeah, @toddbaert @beeme1mr - can we get Dave set up with a repo?

**Comment by toddbaert** [comment]
I think I'd prefer to use hyphens in repo names, but I don't feel strongly about it. I think this is a good place for it, so I will create a repo in this project simply called "golang-sdk" unless there are other suggestions. 

cc @agentgonzo @beeme1mr 

@davejohnston I've invited you to the project. You may want to add yourself to the [interested parties](https://github.com/open-feature/community/blob/main/interested-parties.md)

**Comment by davejohnston** [comment]
@toddbaert Thanks that repo name works for me.   I've raised a PR for the interested-parties.md as well.

**Comment by toddbaert** [comment]
https://github.com/open-feature/golang-sdk

**Comment by toddbaert** [comment]
Closing this since golang SDK is well underway.
