### ISSUE TITLE
Refine Purpose of this Repository, Move Demo Code

### ISSUE THREAD

**Issue by toddbaert** [open-feature/playground#27]
With the project maturing, and the specification, as well as SDKs under active development, I think it's time we refined the focus of this repository.

I think this repository is a great place for research, issues about various SDK implementations before they actually have their own repository, and issues that impact all implementations but don't quite belong in the specification repo.

Until now, this repo has also been used to house the experimental NodeJS/NX project that demonstrates some OpenFeature concepts. I think it's time to migrate that code to it's own repo (perhaps called "getting started" or "understanding OpenFeature" or something like that) with a emphasis on onboarding newcomers to the project, and a telling a straightforward story that provides a clear understanding of the value of OpenFeature, and some of the features it offers. Also - the project would be migrated to use the official Node SDK. This will provide and obvious and attractive entry point to newcomers.

**Comment by beeme1mr** [comment]
The purpose for this repo is for demoing.
