### ISSUE TITLE
OpenFeature Operator Quick Start Fails to start flagd

### ISSUE THREAD

**Issue by marr** [open-feature/playground#298]
I'm following the instructions here https://openfeature.dev/docs/tutorials/open-feature-operator/quick-start/ to play with openfeature and k8s/helm. When I apply the _end-to-end.yaml_ file, I only get one pod running. The logs for the ui service, which is supposed to run on 30002 show the following error:

> [16:43:59.183] ERROR (1): Error resolving flag use-remote-fib-service: No connection established. Last error: connect ECONNREFUSED 127.0.0.1:8013 (2024-06-26T16:42:22.553Z)
> [16:43:59.183] ERROR (1): FlagNotFoundError: No connection established. Last error: connect ECONNREFUSED 127.0.0.1:8013 (2024-06-26T16:42:22.553Z)
>     at GRPCService.onRejected (/opt/playground/node_modules/@openfeature/flagd-provider/index.cjs.js:6013:27)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> [16:43:59.183] ERROR (1): No connection established. Last error: connect ECONNREFUSED 127.0.0.1:8013 (2024-06-26T16:42:22.553Z)
> [16:43:59.186] ERROR (1): Error resolving flag fib-algo: No connection established. Last error: connect ECONNREFUSED 127.0.0.1:8013 (2024-06-26T16:42:22.553Z)
> [16:43:59.187] ERROR (1): FlagNotFoundError: No connection established. Last error: connect ECONNREFUSED 127.0.0.1:8013 (2024-06-26T16:42:22.553Z)
>     at GRPCService.onRejected (/opt/playground/node_modules/@openfeature/flagd-provider/index.cjs.js:6013:27)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> [16:43:59.187] ERROR (1): No connection established. Last error: connect ECONNREFUSED 127.0.0.1:8013 (2024-06-26T16:42:22.553Z)

Is it possible that flagd isn't started during the deployment?

**Comment by beeme1mr** [comment]
Hey @marr, I just ran through the tutorial and it worked as expected. Are you seeing anything else unexpected in the logs? It looks like the flagd service didn't start properly for some reason.
