### ISSUE TITLE
open feature fib3r's provider maybe causing confusion

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/playground#38]
I think it would be good to have a step in the demo which is like:

"There are a bunch of backends for open feature like ${rand.choice(vendorList)}. For the purpose of our demo, we have a very simple json file. Note, that one of the beautiful things about openfeature is that you're not tied to this implementation."

**Comment by justinabrahms** [comment]
Another idea: We could just make a comment or callout at the top of the json section that this isn't openfeature, but is a provider that openfeature abstracts.

**Comment by InTheCloudDan** [comment]
I think a callout at the top of it may help clarify it.

The biggest concern I have is around the targeting of the JSON provider not being clear how it fit into the picture. I'm thinking newcomers to the project may not be able to easily pick up those differences of the API Client vs Provider and where the lines are.

**Comment by beeme1mr** [comment]
Yeah, I think a "provider selector" may work. If a provider other than the JSON one is selected, we could replace the editor with some text explaining how to setup the selected provider.

**Comment by beeme1mr** [comment]
The demo application show support dynamic provider switching. The docs and UI have been updated to reflect that.
