### ISSUE TITLE
Environment dependant flag

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/playground#52]
In an ideal world, software would work the same in dev and prod. In reality, as we all know, environmental differences cause issues.

The idea for this scenario is that a flag is enabled in dev and works perfectly (no degradation). However, when the same flag is enabled in the "prod" environment, it causes an issue (slowdown, error or some other issue).

We can then use mechanisms to highlight that our quality checks passed in dev and so the release was approved to go to prod, but when in prod it caused an issue, so we revert to a similar flow of #51 

Plausible?

**Comment by beeme1mr** [comment]
Yes, this is definitely possible. It actually sounds similar to the session I proposed for KubeCon this year! In my proposal, I talked about the scenario where the code itself is fine but there's a misconfiguration in the prod environment (i.e. invalid auth token). Not only could we make feature flags aware of the environment but we could enable new feature for E2E tests only before rolling them out to real users. That would allow us to test these situations automatically as part of a CI process before enabling them for end users.
