### ISSUE TITLE
Standard demo config tries to start with the Flagsmith provider, does not find it and crashes

### ISSUE THREAD

**Issue by AloisReitbauer** [open-feature/playground#57]
There are actually two issues here:

* The default demo should not start with the flagsmith - or any tool provider requiring additional configuration.
*  If the provider is not found we should default to the NoOps provider but not crash the entire app. 

See error code below

```

> nx run js-flagsmith-v2-provider:build

chunk (runtime: main) main.js (main) 16 KiB [entry] [rendered]

ERROR in packages/js-flagsmith-v2-provider/src/lib/flagsmith-v2.ts:4:10
TS2614: Module '"flagsmithv2"' has no exported member 'Flagsmith'. Did you mean to use 'import Flagsmith from "flagsmithv2"' instead?
    2 | import { JSONValue } from '@openfeature/nodejs-sdk';
    3 | import { EvaluationContext, Provider, ResolutionDetails } from '@openfeature/openfeature-js';
  > 4 | import { Flagsmith } from 'flagsmithv2';
      |          ^^^^^^^^^
    5 |
    6 | type Identity = {
    7 |   identifier?: string;

webpack compiled with 1 error (b28692d1704b621c)

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "app:json-demo" failed

   Failed tasks:
   
   - js-flagsmith-v2-provider:build
   
   Hint: run the command with --verbose for more details.
```

**Comment by toddbaert** [comment]
We are locking the flagsmith SDK to a particular version. Unfortunately, I believe they are un-publishing and re-publishing new breaking changes to this artifact. When those are published, it causes compilation issues. Until that stops, the only thing we can do is remove this artifact from compilation.

**Comment by toddbaert** [comment]
I think the best thing to do might be to pre-build as much of this as possible, and publish the container in the CI. That will simplify things for the demo and remove the compilation burden from the user.

**Comment by beeme1mr** [comment]
I've created an issue to improve the overall demo experience. Once complete, this issue will be resolved.

https://github.com/open-feature/playground/issues/58
