### ISSUE TITLE
Support system properties in context

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/playground#6]
It would be nice to be able to define system properties that are merged with context before a flag evaluation. This could include information such as the version of the application, OS, data center location, etc. Client-side SDKs could set context such as screen size, browser, OS, etc.

Perhaps it could look like this:

```typescript
const { openfeature } = import "@openfeature/openfeature-js";

openfeature.registerGlobalContext({
  "cloud.region": "us-east-1"
})

const client = openfeature.getClient("example");

(async () => {
  // Global and local context would merge before flag evaluation. Locally set
  // context could override global context in case of a collision.
  const enabled = await client.isEnabled("test-feature", { userId: "test-user" });
})()
```

The property name `cloud.region` comes from [OTels semantic convention](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/cloud.md).

**Comment by justinabrahms** [comment]
@moredip Seems fine to me. I'd prefer there be a cap on the number of levels of "flag context" we allow to begin with. Something like 3: system, request, instance. In the above example I provided, system would be `cloud.region`, request would be `ip_is_internal`, and instance would be `userId`.

**Comment by moredip** [comment]
Maybe there's a generic lower-level API that allows arbitrary nesting, but also a higher-level API that builds on top of that with some named scopes (e.g. system and request)? 

I'm not sure of the pros and cons of having that lower-level API a defined part of a spec, vs an implementation detail that might be surfaced in a future version of the spec.

**Comment by moredip** [comment]
FWIW, otel's ContextManager seems to use `async_hooks` [in node](https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-context-async-hooks), and `zone-js` [in browser-land](https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-context-zone).

**Comment by beeme1mr** [comment]
@moredip, this is a good place to explore new concepts. Feel free to open a PR so we can discuss it further.

Something like this could be interesting too:

```typescript
const client = openfeature.getClient("example");

(async () => {
  const testFeature= await client.getVariation("test-feature", { userId: "test-user" });

 if (testFeature.isEnabled()) {
   testFeature.sendEvent("New feature")
  //  Execute new feature
 } else {
   testFeature.sendEvent("Old feature")
  // Execute old feature
 }

  testFeature.end();
})()
```

This may be overengineered too but it would allow you to see the impact of the feature with OTel. Currently, you would see a span representing the flag evaluation but you have less insight into the downstream impact it had.

**Comment by justinabrahms** [comment]
@beeme1mr I generally like the "pass arguments to functions with the things they need" approach. I'd think that the answer would be framework dependent.

Looking at https://koajs.com/, I think we might end up with something like:


```js
const Koa = require('koa');
const app = new Koa();
const { openfeature } = require("@openfeature/openfeature-js");

openfeature.registerGlobalContext({
  "cloud.region": "us-east-1"
})

// add request-scoped variables
app.use(async (ctx, next) => {
  ctx.ffClient = openfeature.getClient('example');
  ctx.ffClient.requestContext({ internal_ip: is_internal(ctx.ip) })
  await next();
});

// response
app.use(async ctx => {
  const greeting = ctx.ffClient.getVariation("greeting", { userId: "test-user" }, "Hello");
  ctx.body = greeting + ' World';
});

app.listen(3000);
```

**Comment by beeme1mr** [comment]
@justinabrahms, got it, thanks. I think the method `requestContext` in the above example is a bit misleading. Perhaps we could call it client scoped context. Here's an example of what it could look like:

```typescript
const Koa = require('koa');
const app = new Koa();
const { openfeature } = require("@openfeature/openfeature-js");

openfeature.registerGlobalContext({
  "cloud.region": "us-east-1"
})

// add request-scoped variables
app.use(async (ctx, next) => {
  ctx.ffClient = openfeature.getClient('example', { internal_ip: is_internal(ctx.ip) });
  await next();
});

// response
app.use(async ctx => {
  const greeting = ctx.ffClient.getVariation("greeting", { userId: "test-user" }, "Hello");
  ctx.body = greeting + ' World';
});

app.listen(3000);
```

We could still introduce request scoped context but it would have to span multiple clients automatically using something like `async_hooks`.

The layer of context could be:
`global` < `client` < `request` < `local`

As context merging could be complex, it would be important to expose debugging information. That way, a developer could understand how a partially property was set.

**Comment by beeme1mr** [comment]
Closing in favor of the issue in the spec.
