### ISSUE TITLE
How would the API respond to being unable to evaluate a flag

### ISSUE THREAD

**Issue by moredip** [open-feature/playground#7]
There are several scenarios where a call to `client.isEnabled(...)` would be unable to return a result. For example:

- there are network connectivity issues to an out-of-process flag evaluation engine
- the flag name is not recognized
- the flag framework has not yet completed initialization (for flag providers that require an async startup)

It seems to me that it would be good to define the semantics for each of these scenarios (plus any other scenarios). Would the call throw an exception? Return a default value?

Similarly, there might be value in some sort of `client.tryIsEnabled` that would check to see if the client would be able to respond, without actually performing the evaluation and recording it in otel, etc. One use case for this API is to build a flag decision multiplexer which would go to various backends for a given flag name and return a decision from the first backend that had one.

**Comment by patricioe** [comment]
Split returns "control" and the reason is provided async via an impression listener under the field `label`.

**Comment by beeme1mr** [comment]
> Split returns "control" and the reason is provided async via an impression listener under the field `label`.

The impression listener concept is interesting. You can see the docs for [Node.js here](https://help.split.io/hc/en-us/articles/360020564931-Node-js-SDK#listener). It may be a good way to expose debugging information without overloading the methods.

We could also leave it up to the individual providers to handle it how they see fit.

**Comment by beeme1mr** [comment]
A default value would be returned. It's also possible to get additional information in the evaluation details such as the reason, error type, and error message.
