### ISSUE TITLE
Usability: Toggling providers loses context

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/playground#75]
So I finish the tutorial and it prompts me to play around with the providers. Nice!

So I  switch from flagd to env. I'm apparently still logged in but now the fib algo looks like it has reset to the slow default version. That said, I can't see anything so I don't know.

Notice the welcome message has also defaulted back but, when I ended the tutorial, I had the new welcome message.

![image](https://user-images.githubusercontent.com/26523841/194018909-cf02aea2-cc7a-49ab-acd6-317618d33faf.png)

Final thought - I can't change any FF values on the env or go-feature-flag selections. It'd be nice to be able to adjust them too.

**Comment by beeme1mr** [comment]
This is working as expected. Please reopen if you have any recommendations for making this step more clear to new users.
